name: wemake python stylecheck

defaults:
  run:
    working-directory: ./bulky-butterflies/src/

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.8]

    steps:
    - name: wemake-python-styleguide
      uses: wemake-services/wemake-python-styleguide
      with:
        reporter: 'github-pr-review'
      env:
        GITHUB_TOKEN: ${{ secrets.github_token }}
