name: Django CI

defaults:
  run:
    working-directory: ./bulky-butterflies/src/

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.8]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install pipenv
      uses: dschep/install-pipenv-action@v1
    - name: Install dependencies
      run: |
        pipenv install --dev --deploy
    - name: Run Tests
      run: |
        pipenv run python manage.py test
    - name: Python Django Coverage GitHub Action
      uses: dc740/django-coveragepy-github-action@0.9
      with:
        # Application
        django-app: 'messenger'
        # Minimum allowed code coverage
        minimum-coverage: 10
